//! Integration coverage for JSON and embedding-vector columns generated by
//! `#[derive(Model)]`, plus nearest-neighbour search — over SQLite here, with a
//! live Postgres variant gated on `SUTEGI_PG_TEST_URL`.
#![cfg(all(feature = "derive", feature = "sqlite"))]

use sutegi::orm::embedding::nearest_typed;
use sutegi::prelude::*;

#[derive(Model, Default, Debug)]
struct Doc {
    #[model(primary)]
    id: i64,
    title: String,
    /// A structured JSON column.
    meta: Json,
    /// A nullable JSON column.
    extra: Option<Json>,
    /// A fixed-dimension embedding column.
    #[model(vector(dim = 3))]
    embedding: Vec<f32>,
}

fn meta(kind: &str, n: i64) -> Json {
    Json::obj(vec![
        ("kind", Json::str(kind)),
        ("rank", Json::int(n)),
        ("tags", Json::arr(vec![Json::str("a"), Json::str("b")])),
    ])
}

fn seeded() -> Db {
    let db = Db::memory().unwrap();
    Doc::migrate(&db).unwrap();
    let rows = [
        ("north", meta("dir", 1), vec![1.0_f32, 0.0, 0.0]),
        ("east", meta("dir", 2), vec![0.0, 1.0, 0.0]),
        ("nn", meta("dir", 3), vec![0.9, 0.1, 0.0]),
    ];
    for (title, m, emb) in rows {
        Doc::create(
            &db,
            &[
                ("title", Value::Text(title.into())),
                ("meta", Value::Json(m)),
                ("embedding", Value::Vector(emb)),
            ],
        )
        .unwrap();
    }
    db
}

#[test]
fn schema_maps_json_and_vector_types() {
    let schema = Doc::schema();
    let ty = |name: &str| schema.columns.iter().find(|c| c.name == name).unwrap().ty;
    assert_eq!(ty("meta"), ColType::Json);
    assert_eq!(ty("extra"), ColType::Json);
    assert!(
        schema
            .columns
            .iter()
            .find(|c| c.name == "extra")
            .unwrap()
            .nullable
    );
    assert_eq!(ty("embedding"), ColType::Vector { dim: Some(3) });

    // Introspection exposes the vector dimension.
    let j = sutegi::orm::schema_json(&schema);
    let emb = j
        .get("columns")
        .and_then(Json::as_array)
        .unwrap()
        .iter()
        .find(|c| c.get("name").and_then(Json::as_str) == Some("embedding"))
        .unwrap();
    assert_eq!(emb.get("type").and_then(Json::as_str), Some("vector"));
    assert_eq!(emb.get("dim").and_then(Json::as_i64), Some(3));
}

#[test]
fn json_and_vector_round_trip_through_sqlite() {
    let db = seeded();
    let doc = Doc::find_typed(&db, Value::Int(1)).unwrap().unwrap();

    // JSON hydrates back into a structured value (parsed from SQLite TEXT).
    assert_eq!(doc.meta.get("kind").and_then(Json::as_str), Some("dir"));
    assert_eq!(doc.meta.get("rank").and_then(Json::as_i64), Some(1));
    assert_eq!(
        doc.meta.get("tags").and_then(Json::as_array).unwrap().len(),
        2
    );
    // The unset nullable JSON column is None.
    assert_eq!(doc.extra, None);
    // The vector round-trips exactly.
    assert_eq!(doc.embedding, vec![1.0, 0.0, 0.0]);

    // to_json nests the JSON column and renders the vector as a number array.
    let j = doc.to_json();
    assert_eq!(
        j.get("meta")
            .and_then(|m| m.get("kind"))
            .and_then(Json::as_str),
        Some("dir")
    );
    assert_eq!(j.get("extra"), Some(&Json::Null));
    let emb = j.get("embedding").and_then(Json::as_array).unwrap();
    assert_eq!(emb.len(), 3);
    assert_eq!(emb[0].as_f64(), Some(1.0));
}

#[test]
fn nearest_ranks_by_cosine_distance() {
    let db = seeded();
    // Query near [1,0,0]: "north" is exact, "nn" ([0.9,0.1,0]) is next, "east" last.
    let hits = nearest_typed::<Doc, _>(
        &db,
        &Doc::query(),
        "embedding",
        &[1.0, 0.0, 0.0],
        2,
        Metric::Cosine,
    )
    .unwrap();
    assert_eq!(hits.len(), 2);
    assert_eq!(hits[0].0.title, "north");
    assert_eq!(hits[1].0.title, "nn");
    assert!(hits[0].1 <= hits[1].1); // ascending distance
}

// --- live Postgres -------------------------------------------------------

/// jsonb columns over Postgres: no extension needed. Runs when the DB is set.
#[cfg(feature = "postgres")]
#[test]
fn jsonb_over_postgres() {
    use sutegi::orm::pg::Pg;

    #[derive(Model, Default)]
    struct Note {
        #[model(primary)]
        id: i64,
        body: String,
        meta: Json,
    }

    let Ok(url) = std::env::var("SUTEGI_PG_TEST_URL") else {
        eprintln!("skipping: SUTEGI_PG_TEST_URL not set");
        return;
    };
    let db = Pg::connect(&url, 2).unwrap();
    db.pool().batch("DROP TABLE IF EXISTS notes").unwrap();
    Note::migrate(&db).unwrap();

    let id = Note::create(
        &db,
        &[
            ("body", Value::Text("hi".into())),
            (
                "meta",
                Value::Json(Json::obj(vec![("pinned", Json::Bool(true))])),
            ),
        ],
    )
    .unwrap();
    // jsonb comes back as structured JSON (decoded by OID), not a string.
    let note = Note::find_typed(&db, Value::Int(id)).unwrap().unwrap();
    assert_eq!(note.id, id);
    assert_eq!(note.body, "hi");
    assert_eq!(note.meta.get("pinned").and_then(Json::as_bool), Some(true));

    db.pool().batch("DROP TABLE notes").unwrap();
}

/// pgvector columns + pushdown search over Postgres. Self-skips if the pgvector
/// extension cannot be enabled, so it stays green on a plain postgres image.
#[cfg(feature = "postgres")]
#[test]
fn vector_over_postgres_with_pgvector() {
    use sutegi::orm::embedding::nearest_pushdown_typed;
    use sutegi::orm::pg::Pg;

    let Ok(url) = std::env::var("SUTEGI_PG_TEST_URL") else {
        eprintln!("skipping: SUTEGI_PG_TEST_URL not set");
        return;
    };
    let db = Pg::connect(&url, 2).unwrap();
    if db
        .pool()
        .batch("CREATE EXTENSION IF NOT EXISTS vector")
        .is_err()
    {
        eprintln!("skipping: pgvector extension unavailable");
        return;
    }
    db.pool().batch("DROP TABLE IF EXISTS docs").unwrap();
    Doc::migrate(&db).unwrap(); // emits `embedding vector(3)`

    for (title, emb) in [
        ("north", vec![1.0_f32, 0.0, 0.0]),
        ("east", vec![0.0, 1.0, 0.0]),
        ("nn", vec![0.9, 0.1, 0.0]),
    ] {
        Doc::create(
            &db,
            &[
                ("title", Value::Text(title.into())),
                ("meta", Value::Json(Json::obj(vec![]))),
                ("embedding", Value::Vector(emb)),
            ],
        )
        .unwrap();
    }

    // Portable brute force and DB pushdown must agree on the ranking.
    let brute = nearest_typed::<Doc, _>(
        &db,
        &Doc::query(),
        "embedding",
        &[1.0, 0.0, 0.0],
        2,
        Metric::Cosine,
    )
    .unwrap();
    let pushed = nearest_pushdown_typed::<Doc, _>(
        &db,
        "docs",
        "embedding",
        &[1.0, 0.0, 0.0],
        2,
        Metric::Cosine,
    )
    .unwrap();
    assert_eq!(brute[0].0.title, "north");
    assert_eq!(pushed[0].0.title, "north");
    assert_eq!(pushed[1].0.title, "nn");

    db.pool().batch("DROP TABLE docs").unwrap();
}
