//! Integration coverage for typed relations + eager loading generated by
//! `#[derive(Model)]`: `has_many`, `has_one`, and `belongs_to`, with the
//! two-query (no N+1) batch loaders and nested `to_json`.
//!
//! Requires `derive` (⇒ `orm`) and the runnable `sqlite` backend.
#![cfg(all(feature = "derive", feature = "sqlite"))]

use sutegi::prelude::*;

#[derive(Model, Default)]
struct User {
    #[model(primary)]
    id: i64,
    name: String,
    #[model(has_many(Post, foreign_key = "user_id"))]
    posts: Vec<Post>,
    #[model(has_one(Profile, foreign_key = "user_id"))]
    profile: Option<Profile>,
}

#[derive(Model, Default)]
struct Post {
    #[model(primary)]
    id: i64,
    user_id: i64,
    title: String,
    #[model(belongs_to(User, foreign_key = "user_id"))]
    author: Option<User>,
}

#[derive(Model, Default)]
struct Profile {
    #[model(primary)]
    id: i64,
    user_id: i64,
    bio: String,
}

fn seeded() -> Db {
    let db = Db::memory().unwrap();
    User::migrate(&db).unwrap();
    Post::migrate(&db).unwrap();
    Profile::migrate(&db).unwrap();

    // Two users; alice has two posts + a profile, bob has one post + no profile.
    let alice = User::create(&db, &[("name", Value::Text("alice".into()))]).unwrap();
    let bob = User::create(&db, &[("name", Value::Text("bob".into()))]).unwrap();
    for (uid, title) in [(alice, "hello"), (alice, "world"), (bob, "solo")] {
        Post::create(
            &db,
            &[
                ("user_id", Value::Int(uid)),
                ("title", Value::Text(title.into())),
            ],
        )
        .unwrap();
    }
    Profile::create(
        &db,
        &[
            ("user_id", Value::Int(alice)),
            ("bio", Value::Text("builds sutegi".into())),
        ],
    )
    .unwrap();
    db
}

#[test]
fn relation_fields_are_not_columns() {
    let user_schema = User::schema();
    let cols: Vec<&str> = user_schema
        .columns
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(cols, vec!["id", "name"]); // posts / profile excluded
    let post_schema = Post::schema();
    let pcols: Vec<&str> = post_schema
        .columns
        .iter()
        .map(|c| c.name.as_str())
        .collect();
    assert_eq!(pcols, vec!["id", "user_id", "title"]); // author excluded
}

#[test]
fn has_many_eager_loads_without_n_plus_one() {
    let db = seeded();
    let users = User::with_posts(&db, User::all_typed(&db).unwrap()).unwrap();

    let alice = users.iter().find(|u| u.name == "alice").unwrap();
    let bob = users.iter().find(|u| u.name == "bob").unwrap();
    let mut alice_titles: Vec<&str> = alice.posts.iter().map(|p| p.title.as_str()).collect();
    alice_titles.sort();
    assert_eq!(alice_titles, vec!["hello", "world"]);
    assert_eq!(bob.posts.len(), 1);
    assert_eq!(bob.posts[0].title, "solo");
}

#[test]
fn has_one_eager_loads_optional_single() {
    let db = seeded();
    let users = User::with_profile(&db, User::all_typed(&db).unwrap()).unwrap();

    let alice = users.iter().find(|u| u.name == "alice").unwrap();
    let bob = users.iter().find(|u| u.name == "bob").unwrap();
    assert_eq!(
        alice.profile.as_ref().map(|p| p.bio.as_str()),
        Some("builds sutegi")
    );
    assert!(bob.profile.is_none());
}

#[test]
fn belongs_to_eager_loads_owner() {
    let db = seeded();
    let posts = Post::with_author(&db, Post::all_typed(&db).unwrap()).unwrap();
    assert_eq!(posts.len(), 3);
    for p in &posts {
        let author = p.author.as_ref().expect("every post has an author");
        match p.title.as_str() {
            "solo" => assert_eq!(author.name, "bob"),
            _ => assert_eq!(author.name, "alice"),
        }
    }
}

#[test]
fn loaded_relations_nest_in_to_json() {
    let db = seeded();
    let users = User::with_posts(&db, User::all_typed(&db).unwrap()).unwrap();
    let users = User::with_profile(&db, users).unwrap();
    let alice = users.iter().find(|u| u.name == "alice").unwrap();

    let j = alice.to_json();
    // has_many nests as an array under the field name...
    let posts = j.get("posts").and_then(Json::as_array).unwrap();
    assert_eq!(posts.len(), 2);
    assert!(posts[0].get("title").and_then(Json::as_str).is_some());
    // ...has_one nests as a single object.
    assert_eq!(
        j.get("profile")
            .and_then(|p| p.get("bio"))
            .and_then(Json::as_str),
        Some("builds sutegi")
    );

    // An unloaded relation serializes as its empty default (no query implied).
    let bare = &User::all_typed(&db).unwrap()[0];
    assert_eq!(
        bare.to_json()
            .get("posts")
            .and_then(Json::as_array)
            .unwrap()
            .len(),
        0
    );
    assert_eq!(bare.to_json().get("profile"), Some(&Json::Null));
}

#[test]
fn empty_parent_set_is_a_noop() {
    let db = seeded();
    // No parents → no query, empty result (guards the IN () edge).
    let none = User::with_posts(&db, Vec::new()).unwrap();
    assert!(none.is_empty());
}

/// The `with_*` loaders are generic over `Backend`, so the same derived code
/// eager-loads over Postgres (with `?`→`$n` translation on `filter_in`). Runs
/// only when `SUTEGI_PG_TEST_URL` is set.
#[cfg(feature = "postgres")]
#[test]
fn relations_eager_load_over_postgres() {
    use sutegi::orm::pg::Pg;

    let Ok(url) = std::env::var("SUTEGI_PG_TEST_URL") else {
        eprintln!("skipping: SUTEGI_PG_TEST_URL not set");
        return;
    };
    let db = Pg::connect(&url, 4).unwrap();
    for t in ["posts", "profiles", "users"] {
        db.pool()
            .batch(&format!("DROP TABLE IF EXISTS {t}"))
            .unwrap();
    }
    User::migrate(&db).unwrap();
    Post::migrate(&db).unwrap();
    Profile::migrate(&db).unwrap();

    let alice = User::create(&db, &[("name", Value::Text("alice".into()))]).unwrap();
    let bob = User::create(&db, &[("name", Value::Text("bob".into()))]).unwrap();
    for (uid, title) in [(alice, "hello"), (alice, "world"), (bob, "solo")] {
        Post::create(
            &db,
            &[
                ("user_id", Value::Int(uid)),
                ("title", Value::Text(title.into())),
            ],
        )
        .unwrap();
    }

    let users = User::with_posts(&db, User::all_typed(&db).unwrap()).unwrap();
    let alice_row = users.iter().find(|u| u.name == "alice").unwrap();
    assert_eq!(alice_row.posts.len(), 2);

    let posts = Post::with_author(&db, Post::all_typed(&db).unwrap()).unwrap();
    assert_eq!(posts.len(), 3);
    assert!(posts.iter().all(|p| p.author.is_some()));

    for t in ["posts", "profiles", "users"] {
        db.pool()
            .batch(&format!("DROP TABLE IF EXISTS {t}"))
            .unwrap();
    }
}
