//! A **durable, cross-pod** job queue backed by PostgreSQL — sutegi's answer to
//! Laravel queues, built to survive restarts and span replicas.
//!
//! Jobs live in a `sutegi_jobs` table. Any number of app pods can enqueue and
//! process from the same queue: workers claim a job atomically with
//! `SELECT … FOR UPDATE SKIP LOCKED`, so two workers never grab the same row.
//! A claim sets a lock timestamp rather than deleting the row, so if a worker
//! crashes mid-job the row becomes visible again after a visibility timeout —
//! giving **at-least-once** delivery. Retries and delayed dispatch are columns,
//! not in-memory timers, so they survive restarts.
//!
//! Jobs are addressed by **name**: you register a handler per job name, and the
//! payload travels as JSON. That's what lets a job enqueued on one pod run on
//! another. Build the queue over a [`sutegi_pg::Pool`]:
//!
//! ```no_run
//! use std::sync::Arc;
//! use sutegi_queue::Queue;
//! use sutegi_json::Json;
//! # fn demo(pool: sutegi_pg::Pool) -> Result<(), String> {
//! let mut queue = Queue::new(pool);
//! queue.register("send_email", |payload: &Json| {
//!     // … do the work, return Err to retry …
//!     Ok(())
//! });
//! queue.migrate()?;
//! queue.dispatch("send_email", Json::obj(vec![("to", Json::str("a@b.c"))]))?;
//!
//! let queue = Arc::new(queue);
//! let _workers = Arc::clone(&queue).start(4); // background workers until dropped
//! # Ok(())
//! # }
//! ```

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::Duration;

use sutegi_json::Json;
use sutegi_pg::{PgValue, Pool};

/// A handler for a named job: receives the decoded JSON payload. Returning
/// `Err` triggers a retry (until the job's attempt budget is exhausted).
pub type Handler = Arc<dyn Fn(&Json) -> Result<(), String> + Send + Sync>;

/// A durable queue over a PostgreSQL connection pool.
pub struct Queue {
    pool: Pool,
    handlers: HashMap<String, Handler>,
    /// How long a claimed-but-unfinished job stays invisible before another
    /// worker may reclaim it (crash recovery).
    visibility_timeout: Duration,
    /// How long an idle worker sleeps before polling for work again.
    poll_interval: Duration,
    /// Base retry backoff; the delay before attempt N is `base * N`.
    retry_backoff: Duration,
}

impl Queue {
    /// Create a queue over `pool` with sensible defaults (30s visibility
    /// timeout, 1s poll interval, 5s base retry backoff).
    pub fn new(pool: Pool) -> Queue {
        Queue {
            pool,
            handlers: HashMap::new(),
            visibility_timeout: Duration::from_secs(30),
            poll_interval: Duration::from_secs(1),
            retry_backoff: Duration::from_secs(5),
        }
    }

    /// Override the visibility timeout (crash-recovery window).
    pub fn visibility_timeout(mut self, d: Duration) -> Queue {
        self.visibility_timeout = d;
        self
    }

    /// Override the idle poll interval.
    pub fn poll_interval(mut self, d: Duration) -> Queue {
        self.poll_interval = d;
        self
    }

    /// Override the base retry backoff.
    pub fn retry_backoff(mut self, d: Duration) -> Queue {
        self.retry_backoff = d;
        self
    }

    /// Register a handler for jobs dispatched under `name`.
    pub fn register(
        &mut self,
        name: impl Into<String>,
        handler: impl Fn(&Json) -> Result<(), String> + Send + Sync + 'static,
    ) {
        self.handlers.insert(name.into(), Arc::new(handler));
    }

    /// The underlying connection pool, for sharing or advanced use.
    pub fn pool(&self) -> &Pool {
        &self.pool
    }

    /// Create the `sutegi_jobs` table if it does not already exist.
    ///
    /// Safe to call from every pod on boot: PostgreSQL can raise a spurious
    /// unique-violation when several backends run `CREATE … IF NOT EXISTS`
    /// against the catalog at the same instant, so that race is treated as
    /// success (the table ends up created either way).
    pub fn migrate(&self) -> Result<(), String> {
        match self.create_schema() {
            Ok(()) => Ok(()),
            Err(e) if e.contains("23505") || e.contains("already exists") => Ok(()),
            Err(e) => Err(e),
        }
    }

    fn create_schema(&self) -> Result<(), String> {
        self.pool.batch(
            "CREATE TABLE IF NOT EXISTS sutegi_jobs (\
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \
                queue TEXT NOT NULL DEFAULT 'default', \
                name TEXT NOT NULL, \
                payload TEXT NOT NULL, \
                attempts INTEGER NOT NULL DEFAULT 0, \
                max_attempts INTEGER NOT NULL DEFAULT 1, \
                run_at TIMESTAMPTZ NOT NULL DEFAULT now(), \
                locked_at TIMESTAMPTZ, \
                failed_at TIMESTAMPTZ, \
                last_error TEXT, \
                created_at TIMESTAMPTZ NOT NULL DEFAULT now()); \
             CREATE INDEX IF NOT EXISTS sutegi_jobs_claim_idx \
                ON sutegi_jobs (run_at) WHERE failed_at IS NULL;",
        )
    }

    /// Enqueue a job to run as soon as a worker is free. Returns its row id.
    pub fn dispatch(&self, name: &str, payload: Json) -> Result<i64, String> {
        self.enqueue(name, payload, 1, Duration::ZERO)
    }

    /// Enqueue a job with a retry budget and an optional start delay.
    pub fn dispatch_with(
        &self,
        name: &str,
        payload: Json,
        max_attempts: u32,
        delay: Duration,
    ) -> Result<i64, String> {
        self.enqueue(name, payload, max_attempts.max(1), delay)
    }

    fn enqueue(
        &self,
        name: &str,
        payload: Json,
        max_attempts: u32,
        delay: Duration,
    ) -> Result<i64, String> {
        let rows = self.pool.query(
            "INSERT INTO sutegi_jobs (name, payload, max_attempts, run_at) \
             VALUES ($1, $2, $3, now() + ($4::bigint * interval '1 millisecond')) \
             RETURNING id",
            &[
                PgValue::Text(name.to_string()),
                PgValue::Text(payload.to_string()),
                PgValue::Int(max_attempts as i64),
                PgValue::Int(delay.as_millis() as i64),
            ],
        )?;
        Ok(rows
            .first()
            .and_then(|r| r.get("id").and_then(Json::as_i64))
            .unwrap_or(0))
    }

    /// Claim and run at most one ready job. Returns `true` if a job ran (so a
    /// caller can keep draining), `false` if the queue was idle.
    pub fn run_once(&self) -> Result<bool, String> {
        let claimed = self.pool.query(
            "UPDATE sutegi_jobs SET locked_at = now(), attempts = attempts + 1 \
             WHERE id = (\
                SELECT id FROM sutegi_jobs \
                WHERE failed_at IS NULL AND run_at <= now() \
                  AND (locked_at IS NULL OR locked_at < now() - ($1::bigint * interval '1 second')) \
                ORDER BY run_at, id \
                FOR UPDATE SKIP LOCKED \
                LIMIT 1) \
             RETURNING id, name, payload, attempts, max_attempts",
            &[PgValue::Int(self.visibility_timeout.as_secs() as i64)],
        )?;

        let Some(job) = claimed.into_iter().next() else {
            return Ok(false);
        };
        let id = job.get("id").and_then(Json::as_i64).unwrap_or(0);
        let name = job
            .get("name")
            .and_then(Json::as_str)
            .unwrap_or("")
            .to_string();
        let attempts = job.get("attempts").and_then(Json::as_i64).unwrap_or(1);
        let max_attempts = job.get("max_attempts").and_then(Json::as_i64).unwrap_or(1);
        let payload = job
            .get("payload")
            .and_then(Json::as_str)
            .and_then(|s| Json::parse(s).ok())
            .unwrap_or(Json::Null);

        let result = match self.handlers.get(&name) {
            Some(handler) => handler(&payload),
            None => Err(format!("no handler registered for job '{name}'")),
        };

        match result {
            Ok(()) => {
                self.pool
                    .execute("DELETE FROM sutegi_jobs WHERE id = $1", &[PgValue::Int(id)])?;
            }
            Err(err) => {
                if attempts >= max_attempts {
                    // Terminal: keep the row as a dead-letter record.
                    self.pool.execute(
                        "UPDATE sutegi_jobs SET failed_at = now(), locked_at = NULL, last_error = $2 \
                         WHERE id = $1",
                        &[PgValue::Int(id), PgValue::Text(err.clone())],
                    )?;
                    eprintln!("[queue] job '{name}' #{id} failed terminally: {err}");
                } else {
                    // Retry: release the lock and schedule a backed-off retry.
                    let backoff_secs = self.retry_backoff.as_secs() as i64 * attempts;
                    self.pool.execute(
                        "UPDATE sutegi_jobs SET locked_at = NULL, last_error = $2, \
                         run_at = now() + ($3::bigint * interval '1 second') WHERE id = $1",
                        &[
                            PgValue::Int(id),
                            PgValue::Text(err),
                            PgValue::Int(backoff_secs),
                        ],
                    )?;
                }
            }
        }
        Ok(true)
    }

    /// A snapshot of queue depth by state, as JSON — wire it into `/__queue`.
    pub fn stats(&self) -> Result<Json, String> {
        let rows = self.pool.query(
            "SELECT \
                count(*) FILTER (WHERE failed_at IS NULL AND run_at <= now() AND locked_at IS NULL) AS ready, \
                count(*) FILTER (WHERE failed_at IS NULL AND locked_at IS NOT NULL) AS running, \
                count(*) FILTER (WHERE failed_at IS NULL AND run_at > now()) AS scheduled, \
                count(*) FILTER (WHERE failed_at IS NOT NULL) AS failed, \
                count(*) AS total \
             FROM sutegi_jobs",
            &[],
        )?;
        let row = rows.into_iter().next().unwrap_or(Json::Null);
        let n = |k: &str| Json::int(row.get(k).and_then(Json::as_i64).unwrap_or(0));
        Ok(Json::obj(vec![
            ("ready", n("ready")),
            ("running", n("running")),
            ("scheduled", n("scheduled")),
            ("failed", n("failed")),
            ("total", n("total")),
        ]))
    }

    /// Spawn `workers` background threads that poll and process jobs until the
    /// returned [`Workers`] handle is dropped (or `stop()` is called).
    pub fn start(self: Arc<Self>, workers: usize) -> Workers {
        let stop = Arc::new(AtomicBool::new(false));
        let mut handles = Vec::new();
        for _ in 0..workers.max(1) {
            let queue = Arc::clone(&self);
            let stop = Arc::clone(&stop);
            handles.push(thread::spawn(move || {
                while !stop.load(Ordering::Relaxed) {
                    match queue.run_once() {
                        Ok(true) => continue, // keep draining while there's work
                        Ok(false) => thread::sleep(queue.poll_interval),
                        Err(e) => {
                            eprintln!("[queue] worker error: {e}");
                            thread::sleep(queue.poll_interval);
                        }
                    }
                }
            }));
        }
        Workers { stop, handles }
    }
}

/// A running set of queue workers. Dropping it (or calling [`stop`]
/// (Workers::stop)) signals shutdown and joins the threads.
pub struct Workers {
    stop: Arc<AtomicBool>,
    handles: Vec<thread::JoinHandle<()>>,
}

impl Workers {
    /// Signal the workers to stop and wait for in-flight jobs to finish.
    pub fn stop(mut self) {
        self.shutdown();
    }

    fn shutdown(&mut self) {
        self.stop.store(true, Ordering::Relaxed);
        for h in self.handles.drain(..) {
            let _ = h.join();
        }
    }
}

impl Drop for Workers {
    fn drop(&mut self) {
        self.shutdown();
    }
}
