//! The pure-std **PostgreSQL** execution layer — sutegi's *multi-pod server*
//! store, backed by the [`sutegi_pg`] driver. Available with the `postgres`
//! feature.
//!
//! This is the cross-pod backend: many app replicas share one database and one
//! durable view of the data, where the [`crate::db::Db`] (SQLite) layer is
//! per-process. It implements the same [`Backend`] trait, so a repository
//! written against one runs on the other by changing only the type it holds.
//!
//! Reach for Postgres when you run more than one instance, need a shared
//! source of truth, or use the durable job queue; reach for SQLite when a
//! single node (or a local KV store) is enough.

use crate::backend::Backend;
use crate::value::{ColType, TableSchema, Value};
use std::cell::RefCell;
use sutegi_json::Json;
use sutegi_pg::Config;

// Re-exported so transaction users and direct pool users don't need a separate
// `sutegi-pg` dependency.
pub use sutegi_pg::{Client, PgValue, Pool};

/// Translate the query builder's `?` placeholders into PostgreSQL's positional
/// `$1, $2, …` form. `?` inside single-quoted string literals is left untouched.
pub fn to_pg_placeholders(sql: &str) -> String {
    let mut out = String::with_capacity(sql.len() + 8);
    let mut n = 0;
    let mut in_str = false;
    for c in sql.chars() {
        match c {
            '\'' => {
                in_str = !in_str;
                out.push(c);
            }
            '?' if !in_str => {
                n += 1;
                out.push('$');
                out.push_str(&n.to_string());
            }
            _ => out.push(c),
        }
    }
    out
}

/// PostgreSQL `CREATE TABLE IF NOT EXISTS` from a schema. Integer primary keys
/// become identity columns; `Real` maps to `DOUBLE PRECISION`.
pub fn create_table_pg(schema: &TableSchema) -> String {
    let mut cols = Vec::new();
    for c in &schema.columns {
        if c.primary && c.ty == ColType::Integer {
            // BY DEFAULT (not ALWAYS) mirrors SQLite's `INTEGER PRIMARY KEY`:
            // auto-generated when omitted, but explicit values are allowed
            // (needed for upsert-by-id and seeding).
            cols.push(format!(
                "  {} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                c.name
            ));
            continue;
        }
        let ty: String = match c.ty {
            ColType::Integer => "BIGINT".into(),
            ColType::Real => "DOUBLE PRECISION".into(),
            ColType::Text => "TEXT".into(),
            ColType::Boolean => "BOOLEAN".into(),
            ColType::Json => "JSONB".into(),
            // pgvector: `vector(dim)` when the dimension is known, else the
            // unconstrained `vector`. Requires the pgvector extension.
            ColType::Vector { dim: Some(d) } => format!("vector({d})"),
            ColType::Vector { dim: None } => "vector".into(),
        };
        let mut def = format!("  {} {}", c.name, ty);
        if c.primary {
            def.push_str(" PRIMARY KEY");
        }
        if !c.nullable && !c.primary {
            def.push_str(" NOT NULL");
        }
        cols.push(def);
    }
    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n{}\n)",
        schema.table,
        cols.join(",\n")
    )
}

fn to_pg_value(v: &Value) -> PgValue {
    match v {
        Value::Null => PgValue::Null,
        Value::Int(i) => PgValue::Int(*i),
        Value::Real(r) => PgValue::Real(*r),
        Value::Text(s) => PgValue::Text(s.clone()),
        Value::Bool(b) => PgValue::Bool(*b),
        Value::Json(j) => PgValue::Json(j.to_string()),
        Value::Vector(vec) => PgValue::Vector(crate::value::vector_to_text(vec)),
    }
}

/// `INSERT … RETURNING pk` with `$n` placeholders — shared by [`Pg`] and [`Tx`].
fn insert_sql(table: &str, cols: &[(&str, Value)], pk: &str) -> (String, Vec<PgValue>) {
    let names: Vec<&str> = cols.iter().map(|(n, _)| *n).collect();
    let placeholders: Vec<String> = (1..=cols.len()).map(|i| format!("${i}")).collect();
    let sql = format!(
        "INSERT INTO {} ({}) VALUES ({}) RETURNING {}",
        table,
        names.join(", "),
        placeholders.join(", "),
        pk
    );
    (sql, cols.iter().map(|(_, v)| to_pg_value(v)).collect())
}

/// `INSERT … ON CONFLICT … DO UPDATE … RETURNING pk` — shared by [`Pg`] / [`Tx`].
fn upsert_sql(
    table: &str,
    cols: &[(&str, Value)],
    conflict: &str,
    pk: &str,
) -> (String, Vec<PgValue>) {
    let names: Vec<&str> = cols.iter().map(|(n, _)| *n).collect();
    let placeholders: Vec<String> = (1..=cols.len()).map(|i| format!("${i}")).collect();
    let updates: Vec<String> = names
        .iter()
        .filter(|n| **n != conflict)
        .map(|n| format!("{n} = EXCLUDED.{n}"))
        .collect();
    let sql = format!(
        "INSERT INTO {} ({}) VALUES ({}) ON CONFLICT ({}) DO UPDATE SET {} RETURNING {}",
        table,
        names.join(", "),
        placeholders.join(", "),
        conflict,
        updates.join(", "),
        pk
    );
    (sql, cols.iter().map(|(_, v)| to_pg_value(v)).collect())
}

/// Extract the `pk` column from a single-row `RETURNING` result.
fn pk_from_rows(rows: &[Json], pk: &str) -> i64 {
    rows.first()
        .and_then(|r| r.get(pk).and_then(Json::as_i64))
        .unwrap_or(0)
}

/// A PostgreSQL-backed handle, cloneable and shareable across threads (it holds
/// a connection [`Pool`]).
#[derive(Clone)]
pub struct Pg {
    pool: Pool,
}

impl Pg {
    /// Wrap an existing connection pool.
    pub fn new(pool: Pool) -> Pg {
        Pg { pool }
    }

    /// Connect using a `postgres://…` URL with a pool of `max_size`.
    pub fn connect(url: &str, max_size: usize) -> Result<Pg, String> {
        Ok(Pg {
            pool: Pool::new(Config::from_url(url)?, max_size),
        })
    }

    /// Build from `DATABASE_URL`/`PG*` environment variables.
    pub fn from_env(max_size: usize) -> Result<Pg, String> {
        Ok(Pg {
            pool: Pool::from_env(max_size)?,
        })
    }

    /// The underlying pool, for queue drivers and advanced use.
    pub fn pool(&self) -> &Pool {
        &self.pool
    }

    /// Run `f` inside a single-connection transaction: `BEGIN`, then `COMMIT`
    /// on `Ok` or `ROLLBACK` on `Err`. The closure receives a [`Tx`], which is
    /// a [`Backend`] pinned to one connection — so the query builder + `Model`
    /// surface all run inside the transaction (unlike a raw `Client`).
    pub fn transaction<T>(&self, f: impl FnOnce(&Tx) -> Result<T, String>) -> Result<T, String> {
        self.pool.with(|client| {
            client.batch("BEGIN")?;
            let tx = Tx {
                client: RefCell::new(client),
            };
            match f(&tx) {
                Ok(value) => {
                    tx.client.borrow_mut().batch("COMMIT")?;
                    Ok(value)
                }
                Err(e) => {
                    let _ = tx.client.borrow_mut().batch("ROLLBACK");
                    Err(e)
                }
            }
        })
    }
}

impl Backend for Pg {
    fn query(&self, sql: &str, params: &[Value]) -> Result<Vec<Json>, String> {
        let bound: Vec<PgValue> = params.iter().map(to_pg_value).collect();
        self.pool.query(&to_pg_placeholders(sql), &bound)
    }

    fn execute(&self, sql: &str, params: &[Value]) -> Result<usize, String> {
        let bound: Vec<PgValue> = params.iter().map(to_pg_value).collect();
        self.pool
            .execute(&to_pg_placeholders(sql), &bound)
            .map(|n| n as usize)
    }

    fn insert(&self, table: &str, cols: &[(&str, Value)], pk: &str) -> Result<i64, String> {
        let (sql, bound) = insert_sql(table, cols, pk);
        Ok(pk_from_rows(&self.pool.query(&sql, &bound)?, pk))
    }

    fn upsert(
        &self,
        table: &str,
        cols: &[(&str, Value)],
        conflict: &str,
        pk: &str,
    ) -> Result<i64, String> {
        let (sql, bound) = upsert_sql(table, cols, conflict, pk);
        Ok(pk_from_rows(&self.pool.query(&sql, &bound)?, pk))
    }

    fn migrate(&self, schema: &TableSchema) -> Result<(), String> {
        self.pool.batch(&create_table_pg(schema))
    }
}

impl crate::backend::Transactional for Pg {
    fn run_in_tx(
        &self,
        f: &mut dyn FnMut(&dyn Backend) -> Result<(), String>,
    ) -> Result<(), String> {
        self.transaction(|tx| f(tx))
    }
}

/// A transaction handle: a [`Backend`] pinned to a single pooled connection for
/// the duration of a [`Pg::transaction`] closure. Uses interior mutability
/// because the trait takes `&self` while the underlying [`Client`] needs
/// `&mut`.
pub struct Tx<'a> {
    client: RefCell<&'a mut Client>,
}

impl Backend for Tx<'_> {
    fn query(&self, sql: &str, params: &[Value]) -> Result<Vec<Json>, String> {
        let bound: Vec<PgValue> = params.iter().map(to_pg_value).collect();
        self.client
            .borrow_mut()
            .query(&to_pg_placeholders(sql), &bound)
    }

    fn execute(&self, sql: &str, params: &[Value]) -> Result<usize, String> {
        let bound: Vec<PgValue> = params.iter().map(to_pg_value).collect();
        self.client
            .borrow_mut()
            .execute(&to_pg_placeholders(sql), &bound)
            .map(|n| n as usize)
    }

    fn insert(&self, table: &str, cols: &[(&str, Value)], pk: &str) -> Result<i64, String> {
        let (sql, bound) = insert_sql(table, cols, pk);
        Ok(pk_from_rows(
            &self.client.borrow_mut().query(&sql, &bound)?,
            pk,
        ))
    }

    fn upsert(
        &self,
        table: &str,
        cols: &[(&str, Value)],
        conflict: &str,
        pk: &str,
    ) -> Result<i64, String> {
        let (sql, bound) = upsert_sql(table, cols, conflict, pk);
        Ok(pk_from_rows(
            &self.client.borrow_mut().query(&sql, &bound)?,
            pk,
        ))
    }

    fn migrate(&self, schema: &TableSchema) -> Result<(), String> {
        self.client.borrow_mut().batch(&create_table_pg(schema))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::value::Column;

    #[test]
    fn placeholder_translation() {
        assert_eq!(
            to_pg_placeholders("SELECT * FROM t WHERE a = ? AND b = ?"),
            "SELECT * FROM t WHERE a = $1 AND b = $2"
        );
        // `?` inside a string literal is preserved.
        assert_eq!(
            to_pg_placeholders("SELECT '? literal' FROM t WHERE a = ?"),
            "SELECT '? literal' FROM t WHERE a = $1"
        );
    }

    #[test]
    fn pg_ddl_uses_identity_and_double() {
        let schema = TableSchema {
            table: "todos",
            columns: vec![
                Column {
                    name: "id",
                    ty: ColType::Integer,
                    nullable: false,
                    primary: true,
                },
                Column {
                    name: "title",
                    ty: ColType::Text,
                    nullable: false,
                    primary: false,
                },
                Column {
                    name: "score",
                    ty: ColType::Real,
                    nullable: true,
                    primary: false,
                },
            ],
        };
        let sql = create_table_pg(&schema);
        assert!(sql.contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"));
        assert!(sql.contains("title TEXT NOT NULL"));
        assert!(sql.contains("score DOUBLE PRECISION"));
        assert!(!sql.contains("score DOUBLE PRECISION NOT NULL"));
    }

    #[test]
    fn pg_ddl_maps_json_and_vector() {
        let schema = TableSchema {
            table: "docs",
            columns: vec![
                Column {
                    name: "meta",
                    ty: ColType::Json,
                    nullable: false,
                    primary: false,
                },
                Column {
                    name: "embedding",
                    ty: ColType::Vector { dim: Some(384) },
                    nullable: true,
                    primary: false,
                },
                Column {
                    name: "loose",
                    ty: ColType::Vector { dim: None },
                    nullable: true,
                    primary: false,
                },
            ],
        };
        let sql = create_table_pg(&schema);
        assert!(sql.contains("meta JSONB NOT NULL"));
        assert!(sql.contains("embedding vector(384)"));
        assert!(sql.contains("loose vector"));
        assert!(!sql.contains("loose vector("));
    }

    #[test]
    fn insert_and_upsert_sql_shapes() {
        let (isql, ib) = insert_sql(
            "t",
            &[("a", Value::Int(1)), ("b", Value::Text("x".into()))],
            "id",
        );
        assert_eq!(isql, "INSERT INTO t (a, b) VALUES ($1, $2) RETURNING id");
        assert_eq!(ib.len(), 2);

        let (usql, _) = upsert_sql(
            "t",
            &[("id", Value::Int(1)), ("b", Value::Text("x".into()))],
            "id",
            "id",
        );
        assert_eq!(
            usql,
            "INSERT INTO t (id, b) VALUES ($1, $2) ON CONFLICT (id) DO UPDATE SET b = EXCLUDED.b RETURNING id"
        );
    }
}
